apiVersion: v2
name: infra
description: Shared infrastructure services for Laravel applications
type: application
version: 0.1.0

dependencies:
 - name: mariadb
   version: "^11.0.0"
   repository: https://charts.bitnami.com/bitnami
   condition: mariadb.enabled

 - name: redis
   version: "^17.0.0"
   repository: https://charts.bitnami.com/bitnami
   condition: redis.enabled

 - name: postfix
   version: "^1.0.0"
   repository: https://charts.helm.sh/stable
   condition: mailserver.enabled

 - name: prometheus-stack
   version: "^45.0.0"
   repository: https://prometheus-community.github.io/helm-charts
   condition: monitoring.enabled

 - name: elasticsearch
   version: "^19.0.0"
   repository: https://charts.bitnami.com/bitnami
   condition: logging.enabled

 - name: kibana
   version: "^10.0.0"
   repository: https://charts.bitnami.com/bitnami
   condition: logging.enabled

 - name: filebeat
   version: "^7.17.3"
   repository: https://helm.elastic.co
   condition: logging.enabled

 - name: minio
   version: "^12.0.0"
   repository: https://charts.bitnami.com/bitnami
   condition: storage.enabled