apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ include "laravel-app.fullname" . }}-config
 namespace: {{ .Values.namespace }}
data:
 DB_HOST: {{ .Values.infrastructure.database.host | quote }}
 DB_PORT: {{ .Values.infrastructure.database.port | quote }}
 REDIS_HOST: {{ .Values.infrastructure.redis.host | quote }}
 REDIS_PORT: {{ .Values.infrastructure.redis.port | quote }}
 MAIL_HOST: {{ .Values.infrastructure.mail.host | quote }}
 MAIL_PORT: {{ .Values.infrastructure.mail.port | quote }}
