apiVersion: v2
name: laravel-app
description: A Laravel application with all required services
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
 - name: mariadb
   version: "^11.0.0"
   repository: https://charts.bitnami.com/bitnami
   condition: mariadb.enabled

 - name: redis
   version: "^17.0.0"
   repository: https://charts.bitnami.com/bitnami
   condition: redis.enabled

 - name: postfix
   version: "^1.0.0"
   repository: https://charts.helm.sh/stable
   condition: mailserver.enabled