environment: staging
namespace: staging

mariadb:
 auth:
  database: laravel_staging
  username: laravel_staging
 primary:
  resources:
   requests:
    memory: 256Mi
    cpu: 250m
   limits:
    memory: 512Mi
    cpu: 500m

redis:
 resources:
  requests:
   memory: 128Mi
   cpu: 100m
  limits:
   memory: 256Mi
   cpu: 250m

app:
 replicas: 2
 resources:
  requests:
   memory: 256Mi
   cpu: 250m
  limits:
   memory: 512Mi
   cpu: 500m