apiVersion: v1
kind: Secret
metadata:
 name: infrastructure-secrets
 namespace: {{ .Values.namespace }}
type: Opaque
data:
 MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | b64enc }}
 REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc }}