{{- if (default (dict "enabled" true) .Values.monitoring).enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: infra
 namespace: {{ .Values.namespace }}
spec:
 selector:
  matchLabels:
   type: infrastructure
 endpoints:
  - port: metrics
  {{- end }}