name: Test Charts

on:
 pull_request:
  paths:
   - 'charts/**'

jobs:
 test:
  runs-on: debian-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Set up Helm
     uses: azure/setup-helm@v1
     with:
      version: v3.12.0

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
      python-version: 3.7

   - name: Set up chart-testing
     uses: helm/chart-testing-action@v2.3.1

   - name: Run chart-testing (lint)
     run: ct lint --config ct.yaml

   - name: Create kind cluster
     uses: helm/kind-action@v1.5.0

   - name: Run chart-testing (install)
     run: ct install --config ct.yaml
